backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "appearance" # This is the collection name
    label: "Appearance" # This is the label shown in the CMS
    files:
      - name: "data_appearance" # This is the file name without the extension
        label: "Appearance Configuration" # Label for the file in the CMS
        file: "data/appearance.yml" # Path to your appearance YAML file
        fields:
          - { name: "branding_site_title", label: "Site Title", widget: "string", required: false }
          - { name: "branding_logo", label: "Logo", widget: "image", required: false }
          - { name: "branding_favicon", label: "Favicon", widget: "image", required: false }
          - { name: "branding_logo_width", label: "Logo Width", widget: "number", required: false }
          - { name: "header_top_header_color", label: "Top Header Color", widget: "color", required: false }
          - { name: "header_header_background_color", label: "Header Background Color", widget: "color", required: false }
          - { name: "header_enable_white_text", label: "Enable White Text", widget: "boolean", required: false }
          - { name: "header_enable_white_text_top", label: "Enable White Text (Top)", widget: "boolean", required: false }
          - { name: "header_transparent_background", label: "Transparent Background", widget: "boolean", required: false }
          - { name: "header_call_to_action_link", label: "Call to Action Link", widget: "string", required: false }
          - { name: "header_call_to_action_label", label: "Call to Action Label", widget: "string", required: false }
          - { name: "header_remove_call_to_action", label: "Remove Call to Action", widget: "boolean", required: false }
          - { name: "pages_image", label: "Pages Image", widget: "image", required: false }
          - { name: "colors_primary_button_background_color", label: "Primary Button Background Color", widget: "color", required: false }
          - { name: "colors_primary_button_text_color", label: "Primary Button Text Color", widget: "color", required: false }
          - { name: "colors_accent", label: "Accent Color", widget: "color", required: false }
          - { name: "colors_idx_title_background_color", label: "IDX Title Background Color", widget: "color", required: false }
          - { name: "colors_idx_title_text_color", label: "IDX Title Text Color", widget: "color", required: false }
          - { name: "form_form_disclaimer", label: "Form Disclaimer", widget: "markdown", required: false }
  - name: "home"
    label: "Home Page"
    files:
      - name: "index"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - label: "Home Sections"
            name: "home_sections"
            widget: "list"
            sortable: true
            types:
              - label: "Hero"
                name: "hero"
                widget: "object"
                fields:
                  - label: "Heading"
                    name: "heading"
                    widget: "string"
                    required: false  # Make this field optional
                  - label: "Body"
                    name: "body"
                    widget: "markdown"
                    required: false  # Make this field optional
                  - label: "Button"
                    name: "button"
                    widget: "string"
                    required: false  # Make this field optional
                  - label: "Button Link"
                    name: "button_link"
                    widget: "string"
                    required: false  # Make this field optional
                  - label: "Overlay Color"
                    name: "overlayColor"
                    widget: "color"
                    required: false  # Make this field optional
                    enableAlpha: true
                  - label: "Heading Color"
                    name: "headingColor"
                    widget: "color"
                  - label: "Body Color"
                    name: "bodyColor"
                    widget: "color"
                    required: false  # Make this field optional
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    required: false  # Make this field optional
              - label: "Featured Grid"
                name: "featured_grid"
                widget: "list"
                fields:
                  - {label: "Body", name: "body", widget: "markdown"}
                  - label: "Featured Blocks"
                    name: "featured_blocks"
                    widget: "list"
                    allow_add: true
                    fields:
                      - {label: "Body", name: "body", widget: "markdown"}
                      - {label: "Image", name: "image", widget: "image"}

              - label: "Text and Image"
                name: "text-and-image"
                widget: "object"
                fields:
                  - label: "Reverse Column"
                    name: "reverse_column"
                    widget: "boolean"
                    required: false  # Make this field optional
                  - label: "Body"
                    name: "body"
                    widget: "markdown"
                    required: false  # Make this field optional
                  - label: "Button"
                    name: "button"
                    widget: "string"
                    required: false  # Make this field optional
                  - label: "Button Link"
                    name: "button_link"
                    widget: "string"
                    required: false  # Make this field optional
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    required: false  # Make this field optional
                  - label: "Background Image"
                    name: "background_image"
                    widget: "image"
                    required: false  # Make this field optional
                  - label: "Background Color"
                    name: "background_color"
                    widget: "color"
                    required: false  # Make this field optional
                  - label: "Body Text Color"
                    name: "body_text_color"
                    widget: "color"
                    required: false  # Make this field optional

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}